name: Manual Build HTML
on:
  workflow_dispatch:

jobs:
  GenerateHTML:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_builder_manual.yml@main
   secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
